name=CodexPad
version=2.1.1
author=arex.huang
maintainer=nulllab
sentence=
paragraph=
category=
url=https://github.com/CodexPad/codexpad_arduino_lib
architectures=esp32
includes=codex_pad.h
depends=NimBLE-Arduino (>=2.3.9)